<a href="https://colab.research.google.com/github/evaristo2020/Python-Clases-UTEC-2025/blob/main/%5B5%5D_Programa_Python_UTEC_Sesion06_Sesion07_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## [1] Crear un arreglo NumPy

In [1]:
# Llamar a la librería

import numpy as np

In [2]:
# Crear un arreglo en numpy

arr_1 = np.array([2,4,6])

print(f"El arreglo es \n{arr_1}")
print(f"El tipo de objeto es \n{type(arr_1)}")

El arreglo es 
[2 4 6]
El tipo de objeto es 
<class 'numpy.ndarray'>


In [3]:
# Lista de listas

lista_1 = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]

print(f"La lista es \n{lista_1}")
print(f"El tipo de dato es {type(lista_1)}")


La lista es 
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
El tipo de dato es <class 'list'>


In [4]:
arr_2 = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

print(f"El arreglo es \n{arr_2}")
print(f"El tipo de objeto es {type(arr_2)}")

El arreglo es 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
El tipo de objeto es <class 'numpy.ndarray'>


In [5]:
print(f"La lista es \n{lista_1}")
print(f"El primer elemento de la lista de listas es \n{lista_1[0]}")

print("\n***Operaciones matemática con la lista***")

print(f"\nEl valor mínimo es {min(lista_1[0])}")
print(f"El valor máximo es {max(lista_1[0])}")
print(f"El valor total es {sum(lista_1[0])}")
print(f"La cantidad de elementos es {len(lista_1[0])}")
print(f"El valor promedio es {sum(lista_1[0])/len(lista_1[0])}")


La lista es 
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
El primer elemento de la lista de listas es 
[0, 1, 2, 3]

***Operaciones matemática con la lista***

El valor mínimo es 0
El valor máximo es 3
El valor total es 6
La cantidad de elementos es 4
El valor promedio es 1.5


In [6]:
## Operaciones con 2 listas

l1 = [1,2,3]
l2 = [4,5,6]

print(f"El resultado de trabajar con 2 listas y el símbolo + es \n{l1+l2}")
print(f"\nEl resultado de sumar ambas listas es \n{sum(l1)+sum(l2)}")

El resultado de trabajar con 2 listas y el símbolo + es 
[1, 2, 3, 4, 5, 6]

El resultado de sumar ambas listas es 
21


In [7]:
print(f"Operaciones con arreglos de NumPy")
print(f"\nEl arreglo de numpy es {arr_1}")

Operaciones con arreglos de NumPy

El arreglo de numpy es [2 4 6]


In [8]:
arr_3 = arr_1 + 5
print(f"El arreglo resultante es \n{arr_3}")

El arreglo resultante es 
[ 7  9 11]


In [9]:
# Operaciones matemáticas con arreglos de NumPy
arr_4 = np.array([1,2,3,4,5])
arr_5 = np.array([10,20,30,40,50])

print(f"El primer arreglo es \n{arr_4}")
print(f"\nEl segundo arreglo es \n{arr_5}")


El primer arreglo es 
[1 2 3 4 5]

El segundo arreglo es 
[10 20 30 40 50]


In [10]:
arr_r1 = arr_4 + arr_5
arr_r2 = arr_5 - arr_4

print(f"La suma de ambos arreglos es \n{arr_r1}")
print(f"\nLa diferencia de ambos arreglos es \n{arr_r2}")

La suma de ambos arreglos es 
[11 22 33 44 55]

La diferencia de ambos arreglos es 
[ 9 18 27 36 45]


## Actividad N034

Crear un arreglo en NumPy a partir de la información de la siguiente tabla y nombrarlo como data_array.

In [11]:
from google.colab import files

uploaded = files.upload()

Saving df_texto.csv to df_texto.csv


In [12]:
from IPython.display import Image,display

display(Image(filename='data_array.png'))

FileNotFoundError: [Errno 2] No such file or directory: 'data_array.png'

In [ ]:
data_array = np.array([
    [35, 10, 1, 3500, 12000],
    [50, 25, 3, 6000, 30000],
    [23,  2, 0,   50,  1500],
    [42, 15, 2, 1000,  2800]
])
print(data_array)

In [ ]:
type(data_array)

## [2] Características de un arreglo en NumPy

In [ ]:
arreglo_1 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

print(f"El arreglo es \n{arreglo_1}")

¿Cuántas dimensiones tiene el arreglo?

In [ ]:
print(f"El número de dimensiones del arreglo es {arreglo_1.ndim}")

¿Cuánto es el tamaño de cada dimensión?

In [ ]:
print(f"El tamaño de las dimensiones del arreglo son {arreglo_1.shape}")
print(f"El tipo de objeto es {type(arreglo_1.shape)}")

¿Cuántos elementos tiene el arreglo?

In [ ]:
print(f"El número de elementos del arreglo es {arreglo_1.size}")


¿Qué tipo de dato contiene el arreglo?

In [ ]:
print(f"El tipo de dato del arreglo es {arreglo_1.dtype.name}")


## Actividad N035

In [ ]:
data_array = np.array([
    [35, 10, 1, 3500, 12000],
    [50, 25, 3, 6000, 30000],
    [23,  2, 0,   50,  1500],
    [42, 15, 2, 1000,  2800]
])

print(f"El arreglo es \n{data_array}")
print(f"\nEl número de dimensiones del arreglo es \n{data_array.ndim}")
print(f"\nEl tamaño de las dimensiones del arreglo son \n{data_array.shape}")
print(f"\nEl total de elementos del arreglo es \n{data_array.size}")

## [3] Operaciones matemáticas con arreglos NumPy

In [ ]:
# Arreglos con las mismas dimensiones
arreglo_2 = np.array([11,12,13,14])
arreglo_3 = np.array([1,2,3,4])

In [ ]:
# Suma de arreglos
arreglo_4 = arreglo_2 + arreglo_3
print(f"El resultado de la suma de ambos arreglos es \n{arreglo_4}")

In [ ]:
# Arreglos con las distintas dimensiones
arreglo_2_ = np.array([11,12,13,14])
arreglo_3_ = np.array([1,2,3,4,5])
# Suma de arreglos
arreglo_5 = arreglo_2_ + arreglo_3_
print(f"El resultado de la suma de ambos arreglos es \n{arreglo_5}")

In [15]:
# Arreglos con las mismas dimensiones
arreglo_2 = np.array([11,12,13,14])
arreglo_3 = np.array([1,2,3,4])

arreglo_5 = arreglo_2 - arreglo_3
print(f"El resultado de la diferencia de arreglos es \n{arreglo_5}")

El resultado de la diferencia de arreglos es 
[10 10 10 10]


In [16]:
# Potencia de arreglos

arreglo_6 = arreglo_3 ** 2

print(f"El arreglo original es \n{arreglo_3}")
print(f"El arreglo resultante es \n{arreglo_6}")

El arreglo original es 
[1 2 3 4]
El arreglo resultante es 
[ 1  4  9 16]


In [17]:
# Multiplicación de matrices




mat_A = np.array([[1,1],[0,1]])
mat_B = np.array([[2,0],[3,4]])

# Verificar el tamaño de las dimensiones de las matrices

t_dim_mA = mat_A.shape
t_dim_mB = mat_B.shape

print(f"El tamaño de las dimensiones de la matriz A es {t_dim_mA}")
print(f"El tamaño de las dimensiones de la matriz B es {t_dim_mB}")

El tamaño de las dimensiones de la matriz A es (2, 2)
El tamaño de las dimensiones de la matriz B es (2, 2)


In [18]:
if t_dim_mA[1]==t_dim_mB[0]:
  mat_C = np.dot(mat_A,mat_B)
  print(f"El resultado de la multiplicación de matrices es \n{mat_C}")
else:
  print("No es posible multiplicar las matrices")

El resultado de la multiplicación de matrices es 
[[5 4]
 [3 4]]


In [26]:
m_A=np.array([[1,0,2,],[3,1,1],[2,1,1]])
m_B=np.array([[1,0],[3,1],[2,1]])

In [31]:
t_dim_m_A=m_A.shape
t_dim_m_B=m_B.shape

if t_dim_m_A[1]==t_dim_m_B[0]:
  m_C = np.dot(m_A,m_B)
  print(f"El resultado de la multiplicación de matrices es \n{m_C}")
else:
  print("No es posible multiplicar las matrices")

El resultado de la multiplicación de matrices es 
[[5 2]
 [8 2]
 [7 2]]


# Ejemplo 3# Crear un arreglo con la funcion .arange()

In [36]:
# Crear un arreglo con la funcion .arange()

mat_7=np.arange(15)

print(f"El arreglo es \n{mat_7}")
print(f"\nLa matriz tiene \n{mat_7.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_7.shape}")
print(f"\nLa cantidad de elementos \n{mat_7.size}")

El arreglo es 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

La matriz tiene 
1 dimensiones

La cantidad de dimensione es 
(15,)

La cantidad de elementos 
15


In [37]:
# Matriz de 1 dimension coventir en distintas dimensionalidades

mat_7=mat_7.reshape(3,5)

In [38]:
print(f"El arreglo es \n{mat_7}")
print(f"\nLa matriz tiene \n{mat_7.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_7.shape}")
print(f"\nLa cantidad de elementos \n{mat_7.size}")

El arreglo es 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

La matriz tiene 
2 dimensiones

La cantidad de dimensione es 
(3, 5)

La cantidad de elementos 
15


Ejemplo 4

In [44]:
mat_9=np.zeros((4,4))

print(f"El arreglo es \n{mat_9}")
print(f"\nLa matriz tiene \n{mat_9.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_9.shape}")
print(f"\nLa cantidad de elementos \n{mat_9.size}")

El arreglo es 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

La matriz tiene 
2 dimensiones

La cantidad de dimensione es 
(4, 4)

La cantidad de elementos 
16


Ejemplo 5

In [45]:
# Crear un arreglo con la funcion .linspace()
#50 => pto de partida(incluido)
#60 => pto de llegada(incluido)
#20 => Cantidad de elementos

mat_10=np.linspace(50,60,20)

print(f"El arreglo es \n{mat_10}")
print(f"\nLa matriz tiene \n{mat_10.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_10.shape}")
print(f"\nLa cantidad de elementos \n{mat_10.size}")

El arreglo es 
[50.         50.52631579 51.05263158 51.57894737 52.10526316 52.63157895
 53.15789474 53.68421053 54.21052632 54.73684211 55.26315789 55.78947368
 56.31578947 56.84210526 57.36842105 57.89473684 58.42105263 58.94736842
 59.47368421 60.        ]

La matriz tiene 
1 dimensiones

La cantidad de dimensione es 
(20,)

La cantidad de elementos 
20


In [46]:
mat_10=mat_10.reshape(4,5)

print(f"El arreglo es \n{mat_10}")
print(f"\nLa matriz tiene \n{mat_10.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_10.shape}")
print(f"\nLa cantidad de elementos \n{mat_10.size}")




El arreglo es 
[[50.         50.52631579 51.05263158 51.57894737 52.10526316]
 [52.63157895 53.15789474 53.68421053 54.21052632 54.73684211]
 [55.26315789 55.78947368 56.31578947 56.84210526 57.36842105]
 [57.89473684 58.42105263 58.94736842 59.47368421 60.        ]]

La matriz tiene 
2 dimensiones

La cantidad de dimensione es 
(4, 5)

La cantidad de elementos 
20


In [47]:
mat_10=mat_10.ravel()


print(f"El arreglo es \n{mat_10}")
print(f"\nLa matriz tiene \n{mat_10.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_10.shape}")
print(f"\nLa cantidad de elementos \n{mat_10.size}")



El arreglo es 
[50.         50.52631579 51.05263158 51.57894737 52.10526316 52.63157895
 53.15789474 53.68421053 54.21052632 54.73684211 55.26315789 55.78947368
 56.31578947 56.84210526 57.36842105 57.89473684 58.42105263 58.94736842
 59.47368421 60.        ]

La matriz tiene 
1 dimensiones

La cantidad de dimensione es 
(20,)

La cantidad de elementos 
20


Ejemplo 6

In [50]:
# crear un arreglo con 30 elementos usando.arange
#cambia la dimensionalidad de (2,3,5)
# 3 filas , 5 columnas, 2 matrices

mat_11=np.arange(30).reshape(2,3,5)
print(f"El arreglo es \n{mat_11}")
print(f"\nLa matriz tiene \n{mat_11.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_11.shape}")
print(f"\nLa cantidad de elementos \n{mat_11.size}")

El arreglo es 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

La matriz tiene 
3 dimensiones

La cantidad de dimensione es 
(2, 3, 5)

La cantidad de elementos 
30


Ejercicio propuesto

craer un arreglo con 3 dimensiones, el arreglo debe estar compuesto por valores 0s y debe tener las dimensiones deben tener el siguiente tamanos (6,2,3)


In [56]:
mat_12=np.zeros((6,2,3))

print(f"El arreglo es \n{mat_12}")
print(f"\nLa matriz tiene \n{mat_12.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_12.shape}")
print(f"\nLa cantidad de elementos \n{mat_12.size}")



El arreglo es 
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

La matriz tiene 
3 dimensiones

La cantidad de dimensione es 
(6, 2, 3)

La cantidad de elementos 
36


In [57]:
mat_13=np.arange(36).reshape(6,2,3)

print(f"El arreglo es \n{mat_13}")
print(f"\nLa matriz tiene \n{mat_13.ndim} dimensiones")
print(f"\nLa cantidad de dimensione es \n{mat_13.shape}")
print(f"\nLa cantidad de elementos \n{mat_13.size}")



El arreglo es 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]]]

La matriz tiene 
3 dimensiones

La cantidad de dimensione es 
(6, 2, 3)

La cantidad de elementos 
36


## Actividad 036

In [58]:
import numpy as np
A = np.array([[1, 2, 3],
              [3, 2, 1]])  # Dimensión: 2x3

B = np.array([[0, 2],
              [-1, 1],
              [0, 1]])     # Dimensión: 3x2

# Multiplicación A · B
AB = np.dot(A, B)

# Multiplicación B · A (solo si es compatible)
try:
    BA = np.dot(B, A)
except ValueError as e:
    BA = str(e)

# Mostrar resultados
print("A · B =")
print(AB)

print("\nB · A =")
print(BA)

A · B =
[[-2  7]
 [-2  9]]

B · A =
[[ 6  4  2]
 [ 2  0 -2]
 [ 3  2  1]]


## [4] seleccion de elementos de un arreglo y concatenacion

In [61]:
print (f" Dado el siguiente arreglo: \n{mat_11}")
print (f"\n\n que tiene \n{mat_11.ndim} dimensiones")
print(f"\n el tamano de dimensione es \n{mat_11.shape}")
print(f"\nLa cantidad de elementos \n{mat_11.size}")

 Dado el siguiente arreglo: 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


 que tiene 
3 dimensiones

 el tamano de dimensione es 
(2, 3, 5)

La cantidad de elementos 
30


In [ ]:
print(f"la segunda matriz del arreglo es  \n{mat_13.shape}")

In [64]:
valores=mat_11[0,2,1:4]
print("Valores seleccionados:", valores)


Valores seleccionados: [11 12 13]
