<a href="https://colab.research.google.com/github/evaristo2020/Python-Clases-UTEC-2025/blob/main/%5B5%5D_Programa_Python_UTEC_Sesion06_Sesion07_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## [1] Crear un arreglo NumPy

In [1]:
# Llamar a la librería

import numpy as np

In [2]:
# Crear un arreglo en numpy

arr_1 = np.array([2,4,6])

print(f"El arreglo es \n{arr_1}")
print(f"El tipo de objeto es \n{type(arr_1)}")

El arreglo es 
[2 4 6]
El tipo de objeto es 
<class 'numpy.ndarray'>


In [3]:
# Lista de listas

lista_1 = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]

print(f"La lista es \n{lista_1}")
print(f"El tipo de dato es {type(lista_1)}")


La lista es 
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
El tipo de dato es <class 'list'>


In [4]:
arr_2 = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

print(f"El arreglo es \n{arr_2}")
print(f"El tipo de objeto es {type(arr_2)}")

El arreglo es 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
El tipo de objeto es <class 'numpy.ndarray'>


In [5]:
print(f"La lista es \n{lista_1}")
print(f"El primer elemento de la lista de listas es \n{lista_1[0]}")

print("\n***Operaciones matemática con la lista***")

print(f"\nEl valor mínimo es {min(lista_1[0])}")
print(f"El valor máximo es {max(lista_1[0])}")
print(f"El valor total es {sum(lista_1[0])}")
print(f"La cantidad de elementos es {len(lista_1[0])}")
print(f"El valor promedio es {sum(lista_1[0])/len(lista_1[0])}")


La lista es 
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
El primer elemento de la lista de listas es 
[0, 1, 2, 3]

***Operaciones matemática con la lista***

El valor mínimo es 0
El valor máximo es 3
El valor total es 6
La cantidad de elementos es 4
El valor promedio es 1.5


In [6]:
## Operaciones con 2 listas

l1 = [1,2,3]
l2 = [4,5,6]

print(f"El resultado de trabajar con 2 listas y el símbolo + es \n{l1+l2}")
print(f"\nEl resultado de sumar ambas listas es \n{sum(l1)+sum(l2)}")

El resultado de trabajar con 2 listas y el símbolo + es 
[1, 2, 3, 4, 5, 6]

El resultado de sumar ambas listas es 
21


In [7]:
print(f"Operaciones con arreglos de NumPy")
print(f"\nEl arreglo de numpy es {arr_1}")

Operaciones con arreglos de NumPy

El arreglo de numpy es [2 4 6]


In [8]:
arr_3 = arr_1 + 5
print(f"El arreglo resultante es \n{arr_3}")

El arreglo resultante es 
[ 7  9 11]


In [9]:
# Operaciones matemáticas con arreglos de NumPy
arr_4 = np.array([1,2,3,4,5])
arr_5 = np.array([10,20,30,40,50])

print(f"El primer arreglo es \n{arr_4}")
print(f"\nEl segundo arreglo es \n{arr_5}")


El primer arreglo es 
[1 2 3 4 5]

El segundo arreglo es 
[10 20 30 40 50]


In [10]:
arr_r1 = arr_4 + arr_5
arr_r2 = arr_5 - arr_4

print(f"La suma de ambos arreglos es \n{arr_r1}")
print(f"\nLa diferencia de ambos arreglos es \n{arr_r2}")

La suma de ambos arreglos es 
[11 22 33 44 55]

La diferencia de ambos arreglos es 
[ 9 18 27 36 45]


## Actividad N034

Crear un arreglo en NumPy a partir de la información de la siguiente tabla y nombrarlo como data_array.

In [ ]:
from google.colab import files

uploaded = files.upload()

In [ ]:
from IPython.display import Image,display

display(Image(filename='data_array.png'))

In [ ]:
data_array = np.array([
    [35, 10, 1, 3500, 12000],
    [50, 25, 3, 6000, 30000],
    [23,  2, 0,   50,  1500],
    [42, 15, 2, 1000,  2800]
])
print(data_array)

In [ ]:
type(data_array)

## [2] Características de un arreglo en NumPy

In [ ]:
arreglo_1 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

print(f"El arreglo es \n{arreglo_1}")

¿Cuántas dimensiones tiene el arreglo?

In [ ]:
print(f"El número de dimensiones del arreglo es {arreglo_1.ndim}")

¿Cuánto es el tamaño de cada dimensión?