<a href="https://colab.research.google.com/github/evaristo2020/Python-Clases-UTEC-2025/blob/main/Laboratorio_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Laboratorio 1

In [ ]:
#Empezando a tokenizar:

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
# Estrcutura de datos: Lista

sentences = [
    'Mi comida favorita es el helado',
    '¿A ti también te gusta el helado?',
    '¡A mi perro le gusta el helado!',
    "tu sabor de helado favorito es el chocolate",
    "el chocolate no es bueno para los perros",
    "tu perro, tu gato y tu loro prefieren el brócoli"
]


In [6]:
print(f"el tipo de obsjeto es {type(sentences)}")

el tipo de obsjeto es <class 'list'>


In [7]:
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences) # le entrego a la funcion tokenizer la lista de frases

In [8]:
print(f"el objeto tokenizer es {type(tokenizer)}")

el objeto tokenizer es <class 'keras.src.legacy.preprocessing.text.Tokenizer'>


In [9]:
word_index = tokenizer.word_index
print(word_index)


{'<OOV>': 1, 'el': 2, 'helado': 3, 'tu': 4, 'es': 5, 'mi': 6, 'gusta': 7, 'perro': 8, 'chocolate': 9, 'comida': 10, 'favorita': 11, '¿a': 12, 'ti': 13, 'también': 14, 'te': 15, '¡a': 16, 'le': 17, 'sabor': 18, 'de': 19, 'favorito': 20, 'no': 21, 'bueno': 22, 'para': 23, 'los': 24, 'perros': 25, 'gato': 26, 'y': 27, 'loro': 28, 'prefieren': 29, 'brócoli': 30}


In [10]:
print(f"Wl objetivo word_index es del tipo {type(word_index)}")

Wl objetivo word_index es del tipo <class 'dict'>


In [11]:
print(word_index['mi'])
print(word_index['comida'])
print(word_index['favorita'])
print(word_index['es'])
print(word_index['el'])
print(word_index['helado'])

6
10
11
5
2
3


In [12]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)


[[6, 10, 11, 5, 2, 3], [12, 13, 14, 15, 7, 2, 3], [16, 6, 8, 17, 7, 2, 3], [4, 18, 19, 3, 20, 5, 2, 9], [2, 9, 21, 5, 22, 23, 24, 25], [4, 8, 4, 26, 27, 4, 28, 29, 2, 30]]


In [13]:
print(f"el  obsjeto sequences es del tipo {type(sentences)}")

el  obsjeto sequences es del tipo <class 'list'>


In [19]:
sentences2 = [
    "Me gusta el chocolate caliente",
    "A mis perros y a mi erizo les gustan las croquetas pero mi ardilla prefiere las uvas \
    y a mis gallinas el helado, preferiblemente de vainilla",
    "Aprendamos python con entusiamo",
    "Mi helado y tu perro"
    ]
sequences2 = tokenizer.texts_to_sequences(sentences2)
print(sequences2)


[[1, 7, 2, 9, 1], [1, 1, 25, 27, 1, 6, 1, 1, 1, 1, 1, 1, 6, 1, 1, 1, 1, 27, 1, 1, 1, 2, 3, 1, 19, 1], [1, 1, 1, 1], [6, 3, 27, 4, 8]]


In [20]:
for i in range(len(sentences2)):
  print(sequences2[i])

[1, 7, 2, 9, 1]
[1, 1, 25, 27, 1, 6, 1, 1, 1, 1, 1, 1, 6, 1, 1, 1, 1, 27, 1, 1, 1, 2, 3, 1, 19, 1]
[1, 1, 1, 1]
[6, 3, 27, 4, 8]


In [21]:
#Truncamiento relleno y el uso de OOV
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [22]:
sentences = [
    'Mi comida favorita es el helado',
     '¿A ti también te gusta el helado?',
     '¡A mi perro le gusta el helado!',
     "tu sabor de helado favorito es el chocolate",
     "el chocolate no es bueno para los perros",
     "tu perro, tu gato y tu loro prefieren el brócoli"
]
print(sentences)


['Mi comida favorita es el helado', '¿A ti también te gusta el helado?', '¡A mi perro le gusta el helado!', 'tu sabor de helado favorito es el chocolate', 'el chocolate no es bueno para los perros', 'tu perro, tu gato y tu loro prefieren el brócoli']


In [24]:
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")

In [25]:
tokenizer.fit_on_texts(sentences)

In [26]:
word_index = tokenizer.word_index
print(word_index)


{'<OOV>': 1, 'el': 2, 'helado': 3, 'tu': 4, 'es': 5, 'mi': 6, 'gusta': 7, 'perro': 8, 'chocolate': 9, 'comida': 10, 'favorita': 11, '¿a': 12, 'ti': 13, 'también': 14, 'te': 15, '¡a': 16, 'le': 17, 'sabor': 18, 'de': 19, 'favorito': 20, 'no': 21, 'bueno': 22, 'para': 23, 'los': 24, 'perros': 25, 'gato': 26, 'y': 27, 'loro': 28, 'prefieren': 29, 'brócoli': 30}


In [27]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)


[[6, 10, 11, 5, 2, 3], [12, 13, 14, 15, 7, 2, 3], [16, 6, 8, 17, 7, 2, 3], [4, 18, 19, 3, 20, 5, 2, 9], [2, 9, 21, 5, 22, 23, 24, 25], [4, 8, 4, 26, 27, 4, 28, 29, 2, 30]]


In [28]:
padded = pad_sequences(sequences)
print(f"\nIndice de palabras: \n{word_index}")
print(f"\nSecuencias: \n{sequences}")
print(f"\nRelleno de Secuencias: \n{padded}")


Indice de palabras: 
{'<OOV>': 1, 'el': 2, 'helado': 3, 'tu': 4, 'es': 5, 'mi': 6, 'gusta': 7, 'perro': 8, 'chocolate': 9, 'comida': 10, 'favorita': 11, '¿a': 12, 'ti': 13, 'también': 14, 'te': 15, '¡a': 16, 'le': 17, 'sabor': 18, 'de': 19, 'favorito': 20, 'no': 21, 'bueno': 22, 'para': 23, 'los': 24, 'perros': 25, 'gato': 26, 'y': 27, 'loro': 28, 'prefieren': 29, 'brócoli': 30}

Secuencias: 
[[6, 10, 11, 5, 2, 3], [12, 13, 14, 15, 7, 2, 3], [16, 6, 8, 17, 7, 2, 3], [4, 18, 19, 3, 20, 5, 2, 9], [2, 9, 21, 5, 22, 23, 24, 25], [4, 8, 4, 26, 27, 4, 28, 29, 2, 30]]

Relleno de Secuencias: 
[[ 0  0  0  0  6 10 11  5  2  3]
 [ 0  0  0 12 13 14 15  7  2  3]
 [ 0  0  0 16  6  8 17  7  2  3]
 [ 0  0  4 18 19  3 20  5  2  9]
 [ 0  0  2  9 21  5 22 23 24 25]
 [ 4  8  4 26 27  4 28 29  2 30]]


In [30]:
print(f"el tipo de obsjeto es \n{type(padded)}")

el tipo de obsjeto es 
<class 'numpy.ndarray'>


In [31]:
padded = pad_sequences(sequences, maxlen=15)
print(padded)


[[ 0  0  0  0  0  0  0  0  0  6 10 11  5  2  3]
 [ 0  0  0  0  0  0  0  0 12 13 14 15  7  2  3]
 [ 0  0  0  0  0  0  0  0 16  6  8 17  7  2  3]
 [ 0  0  0  0  0  0  0  4 18 19  3 20  5  2  9]
 [ 0  0  0  0  0  0  0  2  9 21  5 22 23 24 25]
 [ 0  0  0  0  0  4  8  4 26 27  4 28 29  2 30]]


In [32]:
padded = pad_sequences(sequences, maxlen=15, padding="post")
print(padded)


[[ 6 10 11  5  2  3  0  0  0  0  0  0  0  0  0]
 [12 13 14 15  7  2  3  0  0  0  0  0  0  0  0]
 [16  6  8 17  7  2  3  0  0  0  0  0  0  0  0]
 [ 4 18 19  3 20  5  2  9  0  0  0  0  0  0  0]
 [ 2  9 21  5 22 23 24 25  0  0  0  0  0  0  0]
 [ 4  8  4 26 27  4 28 29  2 30  0  0  0  0  0]]


In [33]:
padded = pad_sequences(sequences, maxlen=3)
print(padded)


[[ 5  2  3]
 [ 7  2  3]
 [ 7  2  3]
 [ 5  2  9]
 [23 24 25]
 [29  2 30]]


In [34]:
test_data = [
    "El sabor de helado favorito de mi mejor amigo es el de fresa",
     "el mejor amigo de mi perro es un manatí"
]
print(test_data)


['El sabor de helado favorito de mi mejor amigo es el de fresa', 'el mejor amigo de mi perro es un manatí']


In [35]:
print("<OOV> tiene el numero", word_index['<OOV>'], "en el índice de palabras.")

<OOV> tiene el numero 1 en el índice de palabras.


In [36]:
test_seq = tokenizer.texts_to_sequences(test_data)
print("\nTest secuencia = ", test_seq)



Test secuencia =  [[2, 18, 19, 3, 20, 19, 6, 1, 1, 5, 2, 19, 1], [2, 1, 1, 19, 6, 8, 5, 1, 1]]


In [37]:
for i in test_seq:
  print(f"La secuencia {i} tiene {len(i)} elementos.")

La secuencia [2, 18, 19, 3, 20, 19, 6, 1, 1, 5, 2, 19, 1] tiene 13 elementos.
La secuencia [2, 1, 1, 19, 6, 8, 5, 1, 1] tiene 9 elementos.


In [38]:
padded = pad_sequences(test_seq, maxlen=10)
print("\nRellenando el test de secuencia: ")
print(padded)



Rellenando el test de secuencia: 
[[ 3 20 19  6  1  1  5  2 19  1]
 [ 0  2  1  1 19  6  8  5  1  1]]
